"""empty message

Revision ID: 31ef62c932c8
Revises: 8a3db4581eac
Create Date: 2020-06-06 18:21:02.062197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ef62c932c8'
down_revision = '8a3db4581eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Project', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Project', 'image_url')
    # ### end Alembic commands ###
