"""empty message

Revision ID: 53cf6ae7f4a8
Revises: b0aa94d3fe3a
Create Date: 2020-05-29 01:21:55.808459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cf6ae7f4a8'
down_revision = 'b0aa94d3fe3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'auth0_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_members', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'project_members', 'members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'])
    op.alter_column('projects', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'projects', 'members', ['member_id'], ['id'])
    op.alter_column('topic_comments', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('topic_comments', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'topic_comments', 'members', ['member_id'], ['id'])
    op.create_foreign_key(None, 'topic_comments', 'topics', ['topic_id'], ['id'])
    op.alter_column('topics', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('topics', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'topics', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'topics', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.alter_column('topics', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('topics', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'topic_comments', type_='foreignkey')
    op.drop_constraint(None, 'topic_comments', type_='foreignkey')
    op.alter_column('topic_comments', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('topic_comments', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.alter_column('project_members', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('members', 'auth0_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
